application: battleshipgame-1321
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_file: favicon.ico
  upload: favicon\.ico

- url: /img
  static_dir: static/img

- url: /_ah/spi.*
  script: api.api
  secure: always


libraries:
- name: endpoints
  version: latest