application: battleshipgame-1321
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi.*
  script: api.api
  secure: always

- url: /crons/send_reminder
  script: main.app

- url: /tasks/send_game_move_email
  script: main.app

libraries:
- name: endpoints
  version: latest